### ISSUE TITLE
TypeError: Cannot read property 'Provider' of undefined

### ISSUE THREAD

**Issue by gyx2019** [huangjianke/Gitter#50]
请教一下，我依次

> git clone

> npm install

> npm run dev:weapp

编译完之后，用微信开发者工具打开，报错：
```
thirdScriptError 
 sdk uncaught third Error 
 Cannot read property 'Provider' of undefined 
 TypeError: Cannot read property 'Provider' of undefined
    at http://127.0.0.1:58932/appservice/app.js:41:25
    at require (http://127.0.0.1:58932/appservice/__dev__/WAService.js:1:1277089)
    at <anonymous>:1:1
    at HTMLScriptElement.scriptLoaded (http://127.0.0.1:58932/appservice/appservice?t=1564849570482:13230:21)
    at HTMLScriptElement.script.onload (http://127.0.0.1:58932/appservice/appservice?t=1564849570482:13242:20)
```
求问这个是啥情况。。

**Comment by huangjianke** [comment]
建议升级一下版本试试

https://taro-docs.jd.com/taro/docs/GETTING-STARTED.html

底部有更新教程

**Comment by jonahfang** [comment]
执行 `taro update project`  即可。
